services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Bratislava}
    volumes:
      # Config (SSD)
      - ${APPDATA_PATH:-/opt/homelab/appdata}/transmission:/config
      # Data (HDD) - public folder + personal downloads
      - ${DATA_PATH:-/mnt/data}/users/andrew/OMG:/downloads
    ports:
      - 51413:51413 # BitTorrent TCP
      - 51413:51413/udp # BitTorrent UDP
    networks:
      - traefik-net
    labels:
      # Traefik - HTTP (local)
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`transmission.${LOCAL_DOMAIN:-home.local}`)
      - traefik.http.routers.transmission.entrypoints=web
      - traefik.http.routers.transmission.middlewares=authelia@docker
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      # Traefik - HTTPS (local via split-DNS)
      - traefik.http.routers.transmission-secure.rule=Host(`transmission.${EXTERNAL_DOMAIN:-1218217.xyz}`)
      - traefik.http.routers.transmission-secure.entrypoints=websecure
      - traefik.http.routers.transmission-secure.tls=true
      - traefik.http.routers.transmission-secure.tls.certresolver=cloudflare
      - traefik.http.routers.transmission-secure.middlewares=authelia@docker
      - traefik.http.routers.transmission-secure.service=transmission
      # Homepage
      - homepage.group=Media
      - homepage.name=Torrent OMG
      - homepage.icon=transmission
      - homepage.href=https://transmission.${EXTERNAL_DOMAIN:-1218217.xyz}
      - homepage.description=Torrent client

networks:
  traefik-net:
    external: true
