---
# Authelia Users Database
# Generate password hash with:
#   docker run --rm authelia/authelia:latest authelia crypto hash generate argon2 --password 'your-password'

users:
  admin:
    disabled: false
    displayname: 'Admin'
    password: '$argon2id$v=19$m=65536,t=3,p=4$navtGT8hYA65xbm6oqe2CA$bWsZ6Z22o+5ELJrlIrJC96IRSuZdWqpbLRpy23zE34Y'
    email: 'seigiard@gmail.com'
    groups:
      - 'admins'
      - 'users'

  andrew:
    disabled: false
    displayname: 'Andrew'
    password: '$argon2id$v=19$m=65536,t=3,p=4$navtGT8hYA65xbm6oqe2CA$bWsZ6Z22o+5ELJrlIrJC96IRSuZdWqpbLRpy23zE34Y'
    email: 'andrejborisenko@fastmail.com'
    groups:
      - 'users'

  yuliia:
    disabled: false
    displayname: 'Yuliia'
    password: '$argon2id$v=19$m=65536,t=3,p=4$WbEuRGsOKB7lNN5dvjWrTw$zg2Z/L6jzX8zuRFGvg8rVp2umyCvvwOeAFI4jt2WT04'
    email: 'glenthedeveloper@gmail.com'
    groups:
      - 'users'
