server:
  port: 80
  sources:
    - path: /srv/public
      name: "Public Files"
      config:
        defaultEnabled: true
    - path: /srv/users
      name: "My Files"
      config:
        defaultEnabled: true
        createUserDir: true

userDefaults:
  permissions:
    admin: false
    api: false
    create: true
    modify: true
    delete: true
    share: true
    download: true
    realtime: false

auth:
  adminUsername: admin
  methods:
    proxy:
      enabled: true
      header: "Remote-User"
      createUser: true
    password:
      enabled: false
